# -*- coding: utf-8 -*-
# 大规模词库 · 第 5 部分（补足至 3000+）
# 字段：(w, pos, cn)
EXTRA = [
# ── 地理/天文/自然 ──
("continent","n.","大陆"),("equator","n.","赤道"),("hemisphere","n.","半球"),("glacier","n.","冰川"),
("volcano","n.","火山"),("earthquake","n.","地震"),("valley","n.","山谷"),("canyon","n.","峡谷"),
("desert","n.","沙漠"),("oasis","n.","绿洲"),("prairie","n.","草原"),("swamp","n.","沼泽"),
("coast","n.","海岸"),("harbor","n.","港口"),("peninsula","n.","半岛"),("tundra","n.","苔原"),
("plateau","n.","高原"),("cliff","n.","悬崖"),("cave","n.","洞穴"),("waterfall","n.","瀑布"),
("pond","n.","池塘"),("spring","n.","泉水；春天"),("channel","n.","海峡；频道"),("current","n.","水流；电流"),
("tide","n.","潮汐"),("wave","n.","波浪"),("reef","n.","礁石"),("lagoon","n.","泻湖"),
("galaxy","n.","星系"),("comet","n.","彗星"),("asteroid","n.","小行星"),("eclipse","n.","日/月食"),
("orbit","n.","轨道"),("gravity","n.","重力"),("telescope","n.","望远镜"),("astronaut","n.","宇航员"),
("satellite","n.","卫星"),("rocket","n.","火箭"),("spacecraft","n.","航天器"),("meteor","n.","流星"),
("atmosphere","n.","大气"),("climate","n.","气候"),("forecast","n.","预报"),("season","n.","季节"),
("spring","n.","春"),("summer","n.","夏"),("autumn","n.","秋"),("winter","n.","冬"),
("fossil","n.","化石"),("mineral","n.","矿物"),("crystal","n.","水晶"),("diamond","n.","钻石"),
("gold","n.","黄金"),("silver","n.","银"),("copper","n.","铜"),("iron","n.","铁"),
("steel","n.","钢"),("coal","n.","煤"),("oil","n.","石油"),("gas","n.","气体；汽油"),

# ── 学科/科学 ──
("mathematics","n.","数学"),("physics","n.","物理"),("chemistry","n.","化学"),("biology","n.","生物"),
("geography","n.","地理"),("history","n.","历史"),("philosophy","n.","哲学"),("psychology","n.","心理学"),
("sociology","n.","社会学"),("economics","n.","经济学"),("linguistics","n.","语言学"),("astronomy","n.","天文学"),
("geology","n.","地质学"),("ecology","n.","生态学"),("genetics","n.","遗传学"),("botany","n.","植物学"),
("zoology","n.","动物学"),("anatomy","n.","解剖学"),("microscope","n.","显微镜"),("telescope","n.","望远镜"),
("molecule","n.","分子"),("atom","n.","原子"),("cell","n.","细胞"),("tissue","n.","组织"),
("organism","n.","生物；有机体"),("species","n.","物种"),("evolution","n.","进化"),("gravity","n.","引力"),
("energy","n.","能量"),("matter","n.","物质"),("force","n.","力"),("motion","n.","运动"),
("velocity","n.","速度"),("pressure","n.","压强"),("temperature","n.","温度"),("volume","n.","体积"),
("density","n.","密度"),("mass","n.","质量"),("wave","n.","波"),("frequency","n.","频率"),

# ── 医学/健康细化 ──
("hospital","n.","医院"),("clinic","n.","诊所"),("patient","n.","病人"),("doctor","n.","医生"),
("nurse","n.","护士"),("surgeon","n.","外科医生"),("dentist","n.","牙医"),("pharmacy","n.","药房"),
("medicine","n.","药；医学"),("pill","n.","药丸"),("tablet","n.","药片"),("capsule","n.","胶囊"),
("syringe","n.","注射器"),("bandage","n.","绷带"),("stethoscope","n.","听诊器"),("ambulance","n.","救护车"),
("fever","n.","发烧"),("cough","n.","咳嗽"),("headache","n.","头痛"),("stomachache","n.","胃痛"),
("toothache","n.","牙痛"),("sore throat","n.","喉咙痛"),("cold","n.","感冒"),("flu","n.","流感"),
("allergy","n.","过敏"),("asthma","n.","哮喘"),("diabetes","n.","糖尿病"),("hypertension","n.","高血压"),
("cancer","n.","癌症"),("tumor","n.","肿瘤"),("virus","n.","病毒"),("bacteria","n.","细菌"),
("infection","n.","感染"),("immune","adj.","免疫的"),("vaccine","n.","疫苗"),("symptom","n.","症状"),
("diagnosis","n.","诊断"),("prescription","n.","处方"),("surgery","n.","手术"),("therapy","n.","治疗"),
("rehabilitation","n.","康复"),("wheelchair","n.","轮椅"),("crutch","n.","拐杖"),("cast","n.","石膏"),
("organ","n.","器官"),("lung","n.","肺"),("liver","n.","肝"),("kidney","n.","肾"),
("stomach","n.","胃"),("intestine","n.","肠"),("vein","n.","静脉"),("artery","n.","动脉"),

# ── 运动/游戏 ──
("sport","n.","运动"),("athlete","n.","运动员"),("competition","n.","比赛"),("champion","n.","冠军"),
("medal","n.","奖牌"),("tournament","n.","锦标赛"),("referee","n.","裁判"),("coach","n.","教练"),
("team","n.","队伍"),("goal","n.","进球；目标"),("score","n.","得分"),("tie","n.","平局"),
("football","n.","足球"),("soccer","n.","足球"),("basketball","n.","篮球"),("volleyball","n.","排球"),
("tennis","n.","网球"),("badminton","n.","羽毛球"),("table tennis","n.","乒乓球"),("baseball","n.","棒球"),
("golf","n.","高尔夫"),("skiing","n.","滑雪"),("skating","n.","滑冰"),("swimming","n.","游泳"),
("boxing","n.","拳击"),("wrestling","n.","摔跤"),("cycling","n.","骑自行车"),("marathon","n.","马拉松"),
("gym","n.","健身房"),("dumbbell","n.","哑铃"),("treadmill","n.","跑步机"),("racket","n.","球拍"),
("ball","n.","球"),("bat","n.","球棒"),("net","n.","网"),("court","n.","球场"),
("chess","n.","国际象棋"),("puzzle","n.","谜题"),("card","n.","卡片；纸牌"),("dice","n.","骰子"),
("board game","n.","桌游"),("video game","n.","电子游戏"),("tournament","n.","联赛"),("match","n.","比赛"),

# ── 音乐/艺术/文学 ──
("music","n.","音乐"),("song","n.","歌曲"),("melody","n.","旋律"),("rhythm","n.","节奏"),
("lyrics","n.","歌词"),("instrument","n.","乐器"),("guitar","n.","吉他"),("piano","n.","钢琴"),
("violin","n.","小提琴"),("drum","n.","鼓"),("flute","n.","长笛"),("trumpet","n.","小号"),
("concert","n.","音乐会"),("orchestra","n.","管弦乐队"),("choir","n.","合唱团"),("opera","n.","歌剧"),
("ballet","n.","芭蕾"),("jazz","n.","爵士"),("rock","n.","摇滚"),("pop","n.","流行乐"),
("folk","n.","民谣"),("classical","adj.","古典的"),("band","n.","乐队"),("singer","n.","歌手"),
("composer","n.","作曲家"),("album","n.","专辑"),("record","n.","唱片"),("tune","n.","曲调"),
("art","n.","艺术"),("painting","n.","绘画"),("sculpture","n.","雕塑"),("photography","n.","摄影"),
("exhibition","n.","展览"),("gallery","n.","画廊"),("museum","n.","博物馆"),("theater","n.","剧院"),
("drama","n.","戏剧"),("comedy","n.","喜剧"),("tragedy","n.","悲剧"),("novel","n.","小说"),
("poem","n.","诗"),("essay","n.","散文；论文"),("biography","n.","传记"),("fiction","n.","小说"),
("chapter","n.","章节"),("author","n.","作者"),("editor","n.","编辑"),("publisher","n.","出版商"),
("stage","n.","舞台"),("script","n.","剧本"),("actor","n.","演员"),("actress","n.","女演员"),
("director","n.","导演"),("audience","n.","观众"),("review","n.","评论"),("critic","n.","评论家"),

# ── 法律/政治/社会 ──
("law","n.","法律"),("lawyer","n.","律师"),("judge","n.","法官"),("court","n.","法庭"),
("trial","n.","审判"),("verdict","n.","裁决"),("sentence","n.","判决"),("prison","n.","监狱"),
("crime","n.","犯罪"),("criminal","n.","罪犯"),("police","n.","警察"),("detective","n.","侦探"),
("fine","n.","罚款"),("lawsuit","n.","诉讼"),("witness","n.","证人"),("evidence","n.","证据"),
("rights","n.","权利"),("freedom","n.","自由"),("democracy","n.","民主"),("election","n.","选举"),
("vote","n.","投票"),("candidate","n.","候选人"),("parliament","n.","议会"),("government","n.","政府"),
("president","n.","总统；校长"),("minister","n.","部长"),("senator","n.","参议员"),("mayor","n.","市长"),
("policy","n.","政策"),("tax","n.","税"),("welfare","n.","福利"),("immigration","n.","移民"),
("citizen","n.","公民"),("constitution","n.","宪法"),("reform","n.","改革"),("protest","n.","抗议"),
("movement","n.","运动"),("charity","n.","慈善"),("volunteer","n.","志愿者"),("donation","n.","捐赠"),

# ── 金融/商业细化 ──
("bank","n.","银行"),("account","n.","账户"),("savings","n.","储蓄"),("loan","n.","贷款"),
("mortgage","n.","按揭"),("interest","n.","利息"),("investment","n.","投资"),("stock","n.","股票"),
("bond","n.","债券"),("fund","n.","基金"),("insurance","n.","保险"),("premium","n.","保费"),
("profit","n.","利润"),("loss","n.","亏损"),("revenue","n.","收入"),("expense","n.","支出"),
("budget","n.","预算"),("salary","n.","薪水"),("wage","n.","工资"),("bonus","n.","奖金"),
("tax","n.","税"),("invoice","n.","发票"),("receipt","n.","收据"),("currency","n.","货币"),
("dollar","n.","美元"),("euro","n.","欧元"),("yuan","n.","元"),("price","n.","价格"),
("cost","n.","成本"),("value","n.","价值"),("wealth","n.","财富"),("poverty","n.","贫困"),
("company","n.","公司"),("corporation","n.","企业"),("firm","n.","商行"),("factory","n.","工厂"),
("market","n.","市场"),("trade","n.","贸易"),("export","n.","出口"),("import","n.","进口"),
("brand","n.","品牌"),("product","n.","产品"),("customer","n.","顾客"),("client","n.","客户"),
("merchant","n.","商人"),("retail","n.","零售"),("wholesale","n.","批发"),("auction","n.","拍卖"),

# ── 交通/旅行细化 ──
("car","n.","汽车"),("bus","n.","公交车"),("train","n.","火车"),("subway","n.","地铁"),
("taxi","n.","出租车"),("bicycle","n.","自行车"),("motorcycle","n.","摩托车"),("airplane","n.","飞机"),
("ship","n.","船"),("boat","n.","小船"),("ferry","n.","渡轮"),("helicopter","n.","直升机"),
("station","n.","车站"),("airport","n.","机场"),("terminal","n.","航站楼"),("ticket","n.","票"),
("passport","n.","护照"),("visa","n.","签证"),("luggage","n.","行李"),("suitcase","n.","行李箱"),
("backpack","n.","背包"),("map","n.","地图"),("guide","n.","导游；指南"),("tour","n.","旅行团"),
("journey","n.","旅程"),("trip","n.","旅行"),("voyage","n.","航行"),("cruise","n.","游轮"),
("hotel","n.","酒店"),("hostel","n.","青年旅舍"),("resort","n.","度假村"),("camping","n.","露营"),
("destination","n.","目的地"),("itinerary","n.","行程"),("customs","n.","海关"),("border","n.","边境"),

# ── 烹饪/餐饮细化 ──
("chef","n.","厨师"),("recipe","n.","食谱"),("ingredient","n.","食材"),("seasoning","n.","调料"),
("flavor","n.","风味"),("taste","n.","味道"),("aroma","n.","香气"),("menu","n.","菜单"),
("appetizer","n.","开胃菜"),("main course","n.","主菜"),("dessert","n.","甜点"),("beverage","n.","饮料"),
("wine","n.","葡萄酒"),("beer","n.","啤酒"),("cocktail","n.","鸡尾酒"),("coffee","n.","咖啡"),
("tea","n.","茶"),("snack","n.","零食"),("pastry","n.","糕点"),("bread","n.","面包"),
("noodle","n.","面条"),("rice","n.","米饭"),("soup","n.","汤"),("salad","n.","沙拉"),
("sandwich","n.","三明治"),("burger","n.","汉堡"),("pizza","n.","披萨"),("sushi","n.","寿司"),
("steak","n.","牛排"),("seafood","n.","海鲜"),("vegetarian","n.","素食者"),("vegan","n.","纯素者"),

# ── 常见动词补充 ──
("accompany","v.","陪伴"),("accumulate","v.","积累"),("adapt","v.","适应"),("adopt","v.","采纳；收养"),
("advise","v.","建议"),("advocate","v.","提倡"),("allocate","v.","分配"),("anticipate","v.","预期"),
("appoint","v.","任命"),("assemble","v.","组装"),("assign","v.","分配；指派"),("assist","v.","协助"),
("assume","v.","假定"),("assure","v.","确保"),("attain","v.","达到"),("attribute","v.","归因于"),
("authorize","v.","授权"),("automate","v.","使自动化"),("avert","v.","避免"),("ban","v.","禁止"),
("bypass","v.","绕过"),("cancel","v.","取消"),("certify","v.","证明"),("classify","v.","分类"),
("compensate","v.","补偿"),("compile","v.","编译；汇编"),("comply","v.","遵守"),("conceal","v.","隐藏"),
("concede","v.","承认；让步"),("condemn","v.","谴责"),("conduct","v.","进行；引导"),("confess","v.","承认；忏悔"),
("confide","v.","吐露"),("conform","v.","符合"),("confront","v.","面对"),("conserve","v.","保护；保存"),
("consolidate","v.","巩固"),("constitute","v.","构成"),("constrain","v.","约束"),("construct","v.","建造"),
("consult","v.","咨询"),("consume","v.","消耗"),("contend","v.","主张；竞争"),("contribute","v.","贡献"),
("convey","v.","传达"),("convict","v.","定罪"),("coordinate","v.","协调"),("correlate","v.","关联"),
("correspond","v.","通信；相符"),("criticize","v.","批评"),("culminate","v.","达到顶点"),("cultivate","v.","培养；耕种"),
("deceive","v.","欺骗"),("deceive","v.","欺骗"),("decline","v.","下降；婉拒"),("dedicate","v.","致力于"),
("deduce","v.","推断"),("defend","v.","辩护；保卫"),("define","v.","定义"),("delegate","v.","委派"),
("deliberate","v.","深思；蓄意"),("demonstrate","v.","演示；示威"),("denote","v.","表示"),("deposit","v.","存放；存款"),
("derive","v.","源于；获得"),("descend","v.","下降"),("deserve","v.","应得"),("designate","v.","指定"),
("detect","v.","检测"),("deter","v.","阻止"),("deviate","v.","偏离"),("diagnose","v.","诊断"),
("differentiate","v.","区分"),("dilute","v.","稀释"),("disclose","v.","披露"),("discourage","v.","使气馁"),
("discriminate","v.","歧视；区分"),("dispose","v.","处理"),("dispute","v.","争议"),("dissolve","v.","溶解；解散"),
("distinguish","v.","区分"),("distribute","v.","分发"),("divert","v.","转移"),("dominate","v.","主导"),
("donate","v.","捐赠"),("draft","v.","起草"),("dwell","v.","居住；详述"),("elevate","v.","提升"),
("elicit","v.","引出"),("eliminate","v.","消除"),("embody","v.","体现"),("emphasize","v.","强调"),
("endorse","v.","认可；背书"),("endure","v.","忍受"),("enforce","v.","执行"),("enhance","v.","增强"),
("enlist","v.","征募； enlisted"),("envisage","v.","设想"),("equip","v.","装备"),("eradicate","v.","根除"),
("evacuate","v.","疏散"),("evoke","v.","唤起"),("exceed","v.","超过"),("exclude","v.","排除"),
("execute","v.","执行；处决"),("exemplify","v.","举例说明"),("exert","v.","施加"),("expel","v."," expulsion"),
("expire","v.","到期"),("expose","v.","暴露"),("extract","v.","提取"),("fabricate","v.","制造；捏造"),
("facilitate","v.","促进"),("fascinate","v.","使着迷"),("forecast","v.","预报"),("foresee","v.","预见"),
("forge","v.","锻造；伪造"),("formulate","v.","制定"),("foster","v.","培养； foster"),("found","v.","建立"),
("fulfill","v.","履行；满足"),("gamble","v.","赌博"),("gauge","v.","测量；估计"),("generate","v.","产生"),
("govern","v.","统治；管理"),("graph","v.","图表"),("grant","v.","授予"),("grieve","v.","悲伤"),
("hamper","v.","阻碍"),("harness","v.","利用；驾驭"),("hatch","v.","孵化；策划"),("heighten","v.","提高"),
("hinder","v.","阻碍"),("hinge","v.","取决于"),("hover","v.","盘旋"),("identify","v.","识别"),
("illustrate","v.","说明；举例"),("imitate","v.","模仿"),("impair","v.","损害"),("impart","v.","给予；传授"),
("implement","v.","实施"),("imply","v.","暗示"),("impose","v.","强加"),("impress","v.","给…留下印象"),
("improvise","v.","即兴创作"),("incur","v.","招致"),("infer","v.","推断"),("inflict","v.","施加（伤害）"),
("inhabit","v.","居住于"),("initiate","v.","发起"),("inject","v.","注入"),("innovate","v.","创新"),
("instigate","v.","煽动"),("institute","v.","建立"),("instruct","v.","指示"),("insulate","v.","隔离；绝缘"),
("integrate","v.","整合"),("intercept","v.","拦截"),("intervene","v.","干预"),("intimidate","v.","恐吓"),
("irrigate","v.","灌溉"),("isolate","v.","隔离"),("levy","v.","征收"),("lighten","v.","减轻；照亮"),
("linger","v.","徘徊"),("locate","v.","定位"),("manufacture","v.","制造"),("manipulate","v.","操纵"),
("maximize","v.","最大化"),("mediate","v.","调解"),("memorize","v.","记忆"),("minimize","v.","最小化"),
("mobilize","v.","动员"),("modify","v.","修改"),("monitor","v.","监测"),("motivate","v.","激励"),
("navigate","v.","导航"),("negotiate","v.","谈判"),("nominate","v.","提名"),("notify","v.","通知"),
("offset","v.","抵消"),("omit","v.","省略"),("operate","v.","操作；运转"),("originate","v.","起源"),
("overcome","v.","克服"),("overlook","v.","俯瞰；忽视"),("oversee","v.","监督"),("pace","v.","踱步；定步速"),
("participate","v.","参与"),("penetrate","v.","穿透"),("perceive","v.","感知"),("perfect","v.","完善"),
("perform","v.","执行；表演"),("perish","v.","消亡"),("permit","v.","允许"),("persist","v.","坚持"),
("pertain","v.","有关"),("plead","v.","恳求；辩护"),("plunge","v.","猛跌；投入"),("postpone","v.","推迟"),
("precede","v.","先于"),("predict","v.","预测"),("prepare","v.","准备"),("prescribe","v.","开处方；规定"),
("present","v.","呈现"),("prevail","v.","盛行；占上风"),("prevent","v.","防止"),("proclaim","v.","宣布"),
("profit","v.","获利"),("prohibit","v.","禁止"),("propel","v.","推进"),("propose","v.","提议"),
("prosper","v.","繁荣"),("provoke","v.","挑衅；引起"),("publicize","v.","宣传"),("pursue","v.","追求"),
("qualify","v.","使合格"),("radiate","v.","辐射"),("rebuild","v.","重建"),("recall","v.","回忆；召回"),
("recite","v.","背诵"),("reckon","v.","认为；估算"),("reclaim","v.","收回"),("recover","v.","恢复"),
("rectify","v.","纠正"),("redeem","v.","赎回；弥补"),("reflect","v.","反映"),("reform","v.","改革"),
("refrain","v.","克制"),("refresh","v.","刷新；提神"),("refund","v.","退款"),("regain","v.","重新获得"),
("register","v.","登记"),("regulate","v.","调节；管理"),("rehabilitate","v.","康复；改造"),("reign","v.","统治"),
("reinforce","v.","加强"),("reject","v.","拒绝"),("rejoice","v.","欣喜"),("relapse","v.","复发"),
("relieve","v.","缓解"),("remit","v.","汇款；免除"),("render","v.","提供；使得"),("renew","v.","更新；续期"),
("renounce","v.","放弃；声明放弃"),("renovate","v.","翻新"),("repay","v.","偿还"),("replace","v.","替换"),
("replenish","v.","补充"),("reproduce","v.","繁殖；复制"),("rescue","v.","救援"),("resent","v.","怨恨"),
("reserve","v.","保留；预订"),("reside","v.","居住"),("resign","v.","辞职"),("resolve","v.","解决"),
("restrain","v."," restraint"),("restrict","v.","限制"),("resume","v.","恢复；继续"),("retain","v.","保留"),
("retreat","v.","撤退"),("reveal","v.","揭示"),("revenge","v.","复仇"),("reverse","v.","逆转"),
("revise","v.","修订"),("revive","v.","复兴；复活"),("revoke","v.","撤销"),("revolt","v.","反叛"),
("rotate","v.","旋转"),("sanction","v.","制裁；批准"),("satisfy","v.","满足"),("scatter","v.","散开"),
("scold","v.","责骂"),("scrutinize","v.","细查"),("segregate","v.","隔离"),("sensation","v.","感觉"),
("separate","v.","分开"),("sequester","v.","隔离"),("shatter","v.","粉碎"),("shorten","v.","缩短"),
("simplify","v.","简化"),("single","v.","挑选"),("sketch","v.","素描；草拟"),("smuggle","v.","走私"),
("sow","v.","播种"),("specialize","v.","专攻"),("specify","v.","指定"),("speculate","v.","推测"),
("sponsor","v.","赞助"),("stabilize","v.","稳定"),("stimulate","v.","刺激"),("strengthen","v.","加强"),
("subdivide","v.","再分"),("submit","v.","提交"),("subordinate","v.","使服从"),("subsidize","v.","补贴"),
("substitute","v.","替代"),("sue","v.","起诉"),("summarize","v.","总结"),("supervise","v.","监督"),
("supplement","v.","补充"),("surpass","v.","超越"),("surrender","v.","投降"),("survey","v.","调查"),
("suspend","v.","暂停"),("sustain","v.","维持；支撑"),("swear","v.","发誓；咒骂"),("sympathize","v.","同情"),
("synthesize","v.","合成"),("tariff","v.","征收关税"),("tempt","v.","诱惑"),("terminate","v.","终止"),
("terrify","v.","使恐惧"),("testify","v.","作证"),("threaten","v.","威胁"),("tolerate","v.","容忍"),
("transcend","v.","超越"),("transcribe","v.","转录"),("transfer","v.","转移"),("transit","v.","运输"),
("transplant","v.","移植"),("traverse","v.","穿越"),("trigger","v.","触发"),("trim","v.","修剪"),
("triumph","v.","获胜"),("troubleshoot","v.","排查故障"),("trust","v.","信任"),("undergo","v.","经历"),
("underlie","v.","构成…基础"),("undermine","v.","破坏"),("unfold","v.","展开"),("unify","v.","统一"),
("unleash","v.","释放"),("update","v.","更新"),("upgrade","v.","升级"),("uphold","v.","维护；支持"),
("utilize","v.","利用"),("utter","v.","说出"),("validate","v.","验证"),("vanish","v.","消失"),
("ventilate","v.","通风"),("verify","v.","核实"),("violate","v.","违反"),("visualize","v.","想象；可视化"),
("void","v.","使无效"),("volunteer","v.","自愿"),("warrant","v.","保证；授权"),("weaken","v.","削弱"),
("weave","v.","编织"),("withdraw","v.","撤回"),("withhold","v.","拒绝给予"),("witness","v.","目睹"),
("wrinkle","v.","起皱"),("yield","v.","屈服；产出"),("zap","v.","快速打击"),("zoom","v.","快速移动"),
]
