# -*- coding: utf-8 -*-
# 大规模词库 · 第 1 部分（基础 / 日常高频）
# 字段：(w, pos, cn)  —— 例句与音标由 gen_words.py 自动生成/计算
EXTRA = [
# ── 冠词/代词/基础动词 ──
("the","art.","这；那"),("a","art.","一个"),("an","art.","一个"),
("this","pron.","这"),("that","pron.","那"),("these","pron.","这些"),("those","pron.","那些"),
("i","pron.","我"),("you","pron.","你；你们"),("he","pron.","他"),("she","pron.","她"),
("we","pron.","我们"),("they","pron.","他们"),("it","pron.","它"),
("me","pron.","我（宾格）"),("him","pron.","他（宾格）"),("her","pron.","她（宾格）"),
("us","pron.","我们（宾格）"),("them","pron.","他们（宾格）"),
("my","pron.","我的"),("your","pron.","你的"),("his","pron.","他的"),("our","pron.","我们的"),
("their","pron.","他们的"),("whose","pron.","谁的"),
("be","v.","是；存在"),("am","v.","是（我）"),("is","v.","是（他/她/它）"),("are","v.","是（你/我们/他们）"),
("was","v.","是（过去式）"),("were","v.","是（过去式）"),("been","v.","be的过去分词"),
("have","v.","有"),("has","v.","有（三单）"),("had","v.","有（过去式）"),
("do","v.","做；助动词"),("does","v.","做（三单）"),("did","v.","做（过去式）"),
("will","v.","将"),("would","v.","会；愿意"),("shall","v.","将"),("should","v.","应该"),
("can","v.","能"),("could","v.","能（过去）"),("may","v.","可以"),("might","v.","可能"),
("must","v.","必须"),("need","v.","需要"),("dare","v.","敢"),
("say","v.","说"),("tell","v.","告诉"),("speak","v.","说（语言）"),("talk","v.","交谈"),
("ask","v.","问"),("answer","v.","回答"),("reply","v.","回复"),
("go","v.","去"),("come","v.","来"),("leave","v.","离开"),("arrive","v.","到达"),
("walk","v.","走路"),("run","v.","跑"),("sit","v.","坐"),("stand","v.","站"),
("lie","v.","躺；撒谎"),("sleep","v.","睡觉"),("wake","v.","醒来"),
("eat","v.","吃"),("drink","v.","喝"),("cook","v.","做饭"),("buy","v.","买"),
("sell","v.","卖"),("pay","v.","付款"),("cost","v.","花费"),("save","v.","节省；保存"),
("make","v.","制作；使"),("build","v.","建造"),("create","v.","创造"),("destroy","v.","破坏"),
("get","v.","得到"),("take","v.","拿；花（时间）"),("give","v.","给"),("keep","v.","保持"),
("put","v.","放"),("bring","v.","带来"),("send","v.","寄送"),("carry","v.","搬运"),
("find","v.","找到"),("lose","v.","丢失"),("search","v.","搜寻"),("discover","v.","发现"),
("see","v.","看见"),("look","v.","看"),("watch","v.","观看"),("hear","v.","听见"),
("listen","v.","倾听"),("feel","v.","感觉"),("touch","v.","触摸"),("smell","v.","闻"),
("taste","v.","品尝"),("think","v.","思考"),("know","v.","知道"),("understand","v.","理解"),
("learn","v.","学习"),("teach","v.","教"),("study","v.","学习；研究"),("read","v.","读"),
("write","v.","写"),("draw","v.","画"),("paint","v.","绘画"),("count","v.","数"),
("open","v.","打开"),("close","v.","关闭"),("shut","v.","关上"),("lock","v.","锁"),
("clean","v.","清洁"),("wash","v.","洗"),("dry","v.","弄干"),("fold","v.","折叠"),
("start","v.","开始"),("begin","v.","开始"),("finish","v.","完成"),("end","v.","结束"),
("stop","v.","停止"),("continue","v.","继续"),("repeat","v.","重复"),("try","v.","尝试"),
("fail","v.","失败"),("succeed","v.","成功"),("win","v.","赢"),("lose","v.","输"),
("help","v.","帮助"),("use","v.","使用"),("show","v.","展示"),("hide","v.","隐藏"),
("share","v.","分享"),("borrow","v.","借入"),("lend","v.","借出"),("return","v.","归还；返回"),
("change","v.","改变"),("fix","v.","修理"),("break","v.","打破"),("cut","v.","切"),
("choose","v.","选择"),("pick","v.","挑选"),("decide","v.","决定"),("refuse","v.","拒绝"),
("accept","v.","接受"),("allow","v.","允许"),("forbid","v.","禁止"),("permit","v.","许可"),
("move","v.","移动"),("travel","v.","旅行"),("fly","v.","飞"),("swim","v.","游泳"),
("ride","v.","骑"),("drive","v.","驾驶"),("park","v.","停车"),("wait","v.","等待"),
("hurry","v.","匆忙"),("rest","v.","休息"),("work","v.","工作"),("play","v.","玩；演奏"),
("live","v.","生活；居住"),("die","v.","死"),("grow","v.","成长；种植"),("fall","v.","掉落；跌倒"),
("rise","v.","上升"),("drop","v.","掉落"),("throw","v.","扔"),("catch","v.","抓住"),
("push","v.","推"),("pull","v.","拉"),("climb","v.","爬"),("jump","v.","跳"),
("dance","v.","跳舞"),("sing","v.","唱歌"),("laugh","v.","笑"),("cry","v.","哭"),
("smile","v.","微笑"),("frown","v.","皱眉"),("kiss","v.","亲吻"),("hug","v.","拥抱"),

# ── 基础名词：人/家庭 ──
("person","n.","人"),("people","n.","人们"),("child","n.","孩子"),("children","n.","孩子们"),
("baby","n.","婴儿"),("kid","n.","小孩"),("boy","n.","男孩"),("girl","n.","女孩"),
("man","n.","男人"),("woman","n.","女人"),("men","n.","男人们"),("women","n.","女人们"),
("father","n.","父亲"),("mother","n.","母亲"),("parent","n.","父母"),("son","n.","儿子"),
("daughter","n.","女儿"),("brother","n.","兄弟"),("sister","n.","姐妹"),
("husband","n.","丈夫"),("wife","n.","妻子"),("grandfather","n.","祖父；外祖父"),
("grandmother","n.","祖母；外祖母"),("grandson","n.","孙子；外孙"),("granddaughter","n.","孙女；外孙女"),
("uncle","n.","叔叔；舅舅"),("aunt","n.","阿姨；姑姑"),("cousin","n.","堂/表兄弟姐妹"),
("nephew","n.","侄子；外甥"),("niece","n.","侄女；外甥女"),("friend","n.","朋友"),
("enemy","n.","敌人"),("guest","n.","客人"),("host","n.","主人"),("stranger","n.","陌生人"),
("boss","n.","老板"),("leader","n.","领导"),("member","n.","成员"),("team","n.","团队"),
("group","n.","小组"),("crowd","n.","人群"),("family","n.","家庭"),("couple","n.","夫妇"),

# ── 身体/外貌 ──
("head","n.","头"),("hair","n.","头发"),("face","n.","脸"),("eye","n.","眼睛"),
("ear","n.","耳朵"),("nose","n.","鼻子"),("mouth","n.","嘴"),("lip","n.","嘴唇"),
("tooth","n.","牙齿"),("teeth","n.","牙齿（复数）"),("tongue","n.","舌头"),("neck","n.","脖子"),
("shoulder","n.","肩膀"),("arm","n.","手臂"),("hand","n.","手"),("finger","n.","手指"),
("leg","n.","腿"),("knee","n.","膝盖"),("foot","n.","脚"),("feet","n.","脚（复数）"),
("toe","n.","脚趾"),("back","n.","背；后面"),("stomach","n.","胃；肚子"),("heart","n.","心脏"),
("brain","n.","大脑"),("blood","n.","血液"),("bone","n.","骨头"),("skin","n.","皮肤"),
("body","n.","身体"),("chest","n.","胸部"),("waist","n.","腰"),("muscle","n.","肌肉"),
("beautiful","adj.","美丽的"),("handsome","adj.","英俊的"),("ugly","adj.","丑陋的"),
("tall","adj.","高的"),("short","adj.","矮的；短的"),("fat","adj.","胖的"),("thin","adj.","瘦的"),
("strong","adj.","强壮的"),("weak","adj.","虚弱的"),("sick","adj.","生病的"),("healthy","adj.","健康的"),
("young","adj.","年轻的"),("old","adj.","老的；旧的"),("elderly","adj.","年长的"),

# ── 衣物/饰品 ──
("clothes","n.","衣服"),("shirt","n.","衬衫"),("pants","n.","裤子"),("trousers","n.","长裤"),
("dress","n.","连衣裙"),("skirt","n.","裙子"),("coat","n.","外套"),("jacket","n.","夹克"),
("sweater","n.","毛衣"),("shoes","n.","鞋子"),("boots","n.","靴子"),("hat","n.","帽子"),
("cap","n.","鸭舌帽"),("gloves","n.","手套"),("scarf","n.","围巾"),("socks","n.","袜子"),
("tie","n.","领带"),("belt","n.","皮带"),("pocket","n.","口袋"),("sleeve","n.","袖子"),
("button","n.","纽扣"),("zipper","n.","拉链"),("glasses","n.","眼镜"),("umbrella","n.","雨伞"),
("watch","n.","手表"),("bag","n.","包"),("purse","n.","钱包；手提包"),("wallet","n.","钱包"),

# ── 食物/饮料（基础） ──
("food","n.","食物"),("water","n.","水"),("rice","n.","米饭"),("noodle","n.","面条"),
("bread","n.","面包"),("egg","n.","鸡蛋"),("meat","n.","肉"),("beef","n.","牛肉"),
("pork","n.","猪肉"),("chicken","n.","鸡肉"),("fish","n.","鱼"),("vegetable","n.","蔬菜"),
("fruit","n.","水果"),("apple","n.","苹果"),("banana","n.","香蕉"),("orange","n.","橙子；橙色"),
("grape","n.","葡萄"),("lemon","n.","柠檬"),("pear","n.","梨"),("peach","n.","桃子"),
("strawberry","n.","草莓"),("watermelon","n.","西瓜"),("mango","n.","芒果"),("pineapple","n.","菠萝"),
("tomato","n.","番茄"),("potato","n.","土豆"),("carrot","n.","胡萝卜"),("onion","n.","洋葱"),
("cabbage","n.","卷心菜"),("cucumber","n.","黄瓜"),("mushroom","n.","蘑菇"),("bean","n.","豆"),
("corn","n.","玉米"),("milk","n.","牛奶"),("tea","n.","茶"),("coffee","n.","咖啡"),
("juice","n.","果汁"),("soup","n.","汤"),("sugar","n.","糖"),("salt","n.","盐"),
("pepper","n.","胡椒；辣椒"),("oil","n.","油"),("butter","n.","黄油"),("cheese","n.","奶酪"),
("cake","n.","蛋糕"),("cookie","n.","饼干"),("chocolate","n.","巧克力"),("candy","n.","糖果"),
("ice cream","n.","冰淇淋"),("honey","n.","蜂蜜"),("wine","n.","葡萄酒"),("beer","n.","啤酒"),
("breakfast","n.","早餐"),("lunch","n.","午餐"),("dinner","n.","晚餐"),("meal","n.","一餐"),
("snack","n.","零食"),("bowl","n.","碗"),("plate","n.","盘子"),("cup","n.","杯子"),
("fork","n.","叉子"),("knife","n.","刀"),("spoon","n.","勺子"),("chopsticks","n.","筷子"),
("hungry","adj.","饿的"),("thirsty","adj.","渴的"),("full","adj.","饱的；满的"),("delicious","adj.","美味的"),
("sweet","adj.","甜的"),("sour","adj.","酸的"),("bitter","adj.","苦的"),("spicy","adj.","辣的"),

# ── 自然/天气/动物 ──
("nature","n.","自然"),("sky","n.","天空"),("sun","n.","太阳"),("moon","n.","月亮"),
("star","n.","星星"),("cloud","n.","云"),("rain","n.","雨"),("snow","n.","雪"),
("wind","n.","风"),("storm","n.","暴风雨"),("thunder","n.","雷"),("lightning","n.","闪电"),
("fog","n.","雾"),("rainbow","n.","彩虹"),("weather","n.","天气"),("temperature","n.","温度"),
("hot","adj.","热的"),("cold","adj.","冷的"),("warm","adj.","温暖的"),("cool","adj.","凉爽的"),
("wet","adj.","湿的"),("dry","adj.","干的"),("sunny","adj.","晴朗的"),("rainy","adj.","下雨的"),
("cloudy","adj.","多云的"),("windy","adj.","有风的"),("snowy","adj.","下雪的"),("foggy","adj.","有雾的"),
("mountain","n.","山"),("hill","n.","小山"),("river","n.","河"),("lake","n.","湖"),
("sea","n.","海"),("ocean","n.","海洋"),("beach","n.","海滩"),("island","n.","岛"),
("forest","n.","森林"),("tree","n.","树"),("flower","n.","花"),("grass","n.","草"),
("leaf","n.","叶子"),("root","n.","根"),("plant","n.","植物；种植"),("garden","n.","花园"),
("field","n.","田野"),("stone","n.","石头"),("sand","n.","沙子"),("earth","n.","地球；泥土"),
("fire","n.","火"),("smoke","n.","烟"),("world","n.","世界"),("planet","n.","行星"),
("animal","n.","动物"),("dog","n.","狗"),("cat","n.","猫"),("bird","n.","鸟"),
("fish","n.","鱼"),("horse","n.","马"),("cow","n.","奶牛"),("pig","n.","猪"),
("sheep","n.","羊"),("goat","n.","山羊"),("rabbit","n.","兔子"),("mouse","n.","老鼠"),
("lion","n.","狮子"),("tiger","n.","老虎"),("bear","n.","熊"),("wolf","n.","狼"),
("elephant","n.","大象"),("monkey","n.","猴子"),("snake","n.","蛇"),("fox","n.","狐狸"),
("deer","n.","鹿"),("duck","n.","鸭子"),("goose","n.","鹅"),("bee","n.","蜜蜂"),
("butterfly","n.","蝴蝶"),("ant","n.","蚂蚁"),("spider","n.","蜘蛛"),("insect","n.","昆虫"),
("tail","n.","尾巴"),("wing","n.","翅膀"),("feather","n.","羽毛"),("fur","n.","皮毛"),

# ── 家居/房间/物品 ──
("house","n.","房子"),("home","n.","家"),("room","n.","房间"),("bedroom","n.","卧室"),
("kitchen","n.","厨房"),("bathroom","n.","浴室"),("living room","n.","客厅"),("balcony","n.","阳台"),
("door","n.","门"),("window","n.","窗户"),("wall","n.","墙"),("floor","n.","地板；楼层"),
("ceiling","n.","天花板"),("roof","n.","屋顶"),("stairs","n.","楼梯"),("gate","n.","大门"),
("key","n.","钥匙"),("lock","n.","锁"),("bed","n.","床"),("desk","n.","书桌"),
("chair","n.","椅子"),("table","n.","桌子"),("sofa","n.","沙发"),("shelf","n.","书架；架子"),
("lamp","n.","灯"),("light","n.","光；灯"),("mirror","n.","镜子"),("clock","n.","时钟"),
("phone","n.","电话"),("computer","n.","电脑"),("television","n.","电视"),("camera","n.","相机"),
("radio","n.","收音机"),("fridge","n.","冰箱"),("oven","n.","烤箱"),("stove","n.","炉灶"),
("washing machine","n.","洗衣机"),("fan","n.","风扇"),("air conditioner","n.","空调"),("heater","n.","取暖器"),
("towel","n.","毛巾"),("soap","n.","肥皂"),("toothbrush","n.","牙刷"),("blanket","n.","毯子"),
("pillow","n.","枕头"),("sheet","n.","床单"),("basket","n.","篮子"),("bucket","n.","桶"),
("box","n.","盒子"),("bag","n.","袋子"),("bottle","n.","瓶子"),("can","n.","罐头"),
("tool","n.","工具"),("hammer","n.","锤子"),("nail","n.","钉子"),("rope","n.","绳子"),

# ── 城市/场所/方位 ──
("city","n.","城市"),("town","n.","城镇"),("village","n.","村庄"),("street","n.","街道"),
("road","n.","道路"),("avenue","n.","大道"),("bridge","n.","桥"),("building","n.","建筑物"),
("school","n.","学校"),("office","n.","办公室"),("bank","n.","银行"),("hospital","n.","医院"),
("shop","n.","商店"),("store","n.","商店"),("market","n.","市场"),("restaurant","n.","餐厅"),
("cafe","n.","咖啡馆"),("hotel","n.","酒店"),("library","n.","图书馆"),("museum","n.","博物馆"),
("park","n.","公园"),("garden","n.","花园"),("zoo","n.","动物园"),("cinema","n.","电影院"),
("theater","n.","剧院"),("station","n.","车站"),("airport","n.","机场"),("port","n.","港口"),
("factory","n.","工厂"),("farm","n.","农场"),("church","n.","教堂"),("temple","n.","寺庙"),
("prison","n.","监狱"),("post office","n.","邮局"),("police","n.","警察"),("fire station","n.","消防站"),
("north","n.","北"),("south","n.","南"),("east","n.","东"),("west","n.","西"),
("left","n.","左"),("right","n.","右"),("front","n.","前面"),("back","n.","后面"),
("center","n.","中心"),("corner","n.","角落"),("top","n.","顶部"),("bottom","n.","底部"),
("inside","adv.","在里面"),("outside","adv.","在外面"),("near","prep.","在…附近"),("far","adj.","远的"),
("here","adv.","这里"),("there","adv.","那里"),("around","prep.","在…周围"),("between","prep.","在…之间"),

# ── 时间/数字/颜色/形状 ──
("time","n.","时间"),("day","n.","天"),("night","n.","夜晚"),("morning","n.","早晨"),
("afternoon","n.","下午"),("evening","n.","傍晚"),("week","n.","周"),("month","n.","月"),
("year","n.","年"),("hour","n.","小时"),("minute","n.","分钟"),("second","n.","秒"),
("today","n.","今天"),("tomorrow","n.","明天"),("yesterday","n.","昨天"),("now","adv.","现在"),
("soon","adv.","很快"),("late","adj.","晚的"),("early","adj.","早的"),("always","adv.","总是"),
("often","adv.","经常"),("sometimes","adv.","有时"),("never","adv.","从不"),("already","adv.","已经"),
("still","adv.","仍然"),("before","prep.","在…之前"),("after","prep.","在…之后"),("during","prep.","在…期间"),
("one","num.","一"),("two","num.","二"),("three","num.","三"),("four","num.","四"),
("five","num.","五"),("six","num.","六"),("seven","num.","七"),("eight","num.","八"),
("nine","num.","九"),("ten","num.","十"),("hundred","num.","百"),("thousand","num.","千"),
("first","adj.","第一"),("last","adj.","最后的"),("next","adj.","下一个"),("past","n.","过去"),
("future","n.","未来"),("clock","n.","钟"),("calendar","n.","日历"),("date","n.","日期"),
("red","adj.","红色的"),("blue","adj.","蓝色的"),("green","adj.","绿色的"),("yellow","adj.","黄色的"),
("black","adj.","黑色的"),("white","adj.","白色的"),("gray","adj.","灰色的"),("brown","adj.","棕色的"),
("pink","adj.","粉色的"),("purple","adj.","紫色的"),("gold","adj.","金色的"),("silver","adj.","银色的"),
("color","n.","颜色"),("shape","n.","形状"),("circle","n.","圆"),("square","n.","正方形"),
("triangle","n.","三角形"),("line","n.","线"),("point","n.","点"),("round","adj.","圆的"),
("big","adj.","大的"),("small","adj.","小的"),("long","adj.","长的"),("wide","adj.","宽的"),
("narrow","adj.","窄的"),("deep","adj.","深的"),("shallow","adj.","浅的"),("high","adj.","高的"),
("low","adj.","低的"),("heavy","adj.","重的"),("light","adj.","轻的；亮的"),("fast","adj.","快的"),
("slow","adj.","慢的"),("quick","adj.","迅速的"),("sharp","adj.","锋利的；尖锐的"),("flat","adj.","平坦的"),
]
